import spainFlag from "./spainFlag.png";
import user from "./user.png";

export const countrySummaryData = {
  columns: [
    {
      header: "Country",
      isDefault: true,
      key: "country",
    },
    {
      header: "Currency",
      isDefault: true,
      key: "currency",
    },
    {
      header: "Employees",
      isDefault: true,
      key: "employees",
    },
    {
      header: "Gross Wages",
      isDefault: true,
      key: "grossWages",
    },
    {
      header: "Allowances",
      isDefault: true,
      key: "allowances",
    },
    {
      header: "Expense Reimb.",
      isDefault: true,
      key: "expenseReimb",
    },
    {
      header: "Employer Liability",
      isDefault: true,
      key: "employerLiability",
    },
    {
      header: "Country VAT",
      isDefault: true,
      key: "countryVAT",
    },
    {
      header: "Exchange Rate",
      isDefault: true,
      key: "exchangeRate",
    },
    {
      header: "Total in USD",
      isDefault: true,
      key: "totalInUSD",
    },
  ],
  showDefaultColumn: true,
  data: [
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      employees: "14",
      grossWages: "95,000.00",
      allowances: "13,690.00",
      expenseReimb: "950.00",
      employerLiability: "2,000.00",
      countryVAT: "0.00",
      exchangeRate: "0.75355",
      totalInUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      employees: "14",
      grossWages: "95,000.00",
      allowances: "13,690.00",
      expenseReimb: "950.00",
      employerLiability: "2,000.00",
      countryVAT: "0.00",
      exchangeRate: "0.75355",
      totalInUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      employees: "14",
      grossWages: "95,000.00",
      allowances: "13,690.00",
      expenseReimb: "950.00",
      employerLiability: "2,000.00",
      countryVAT: "0.00",
      exchangeRate: "0.75355",
      totalInUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      employees: "14",
      grossWages: "95,000.00",
      allowances: "13,690.00",
      expenseReimb: "950.00",
      employerLiability: "2,000.00",
      countryVAT: "0.00",
      exchangeRate: "0.75355",
      totalInUSD: "121,411.97",
    },
  ],
};

export const feeSummary = {
  columns: [
    {
      header: "Country",
      isDefault: true,
      key: "country",
    },
    {
      header: "Currency",
      isDefault: true,
      key: "currency",
    },
    {
      header: "Admin Fees",
      isDefault: true,
      key: "adminFees",
    },
    {
      header: "On/Offboardings",
      isDefault: true,
      key: "OnOffboardings",
    },
    {
      header: "FX Rate in %",
      isDefault: true,
      key: "fxRate",
    },
    {
      header: "FX Bill",
      isDefault: true,
      key: "fxBill",
    },
    {
      header: "Benefits",
      isDefault: true,
      key: "benefits",
    },
    {
      header: "Employee Contribution",
      isDefault: true,
      key: "employeeContribution",
    },
    {
      header: "Total in USD",
      isDefault: true,
      key: "totalinUSD",
    },
  ],
  showDefaultColumn: true,
  data: [
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      adminFees: "3,900.00",
      OnOffboardings: "0.00",
      fxRate: "1,5",
      fxBill: "95,000.00",
      benefits: "3,780.00",
      employeeContribution: "0.0",
      totalinUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      adminFees: "3,900.00",
      OnOffboardings: "0.00",
      fxRate: "1,5",
      fxBill: "95,000.00",
      benefits: "3,780.00",
      employeeContribution: "0.0",
      totalinUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      adminFees: "3,900.00",
      OnOffboardings: "0.00",
      fxRate: "1,5",
      fxBill: "95,000.00",
      benefits: "3,780.00",
      employeeContribution: "0.0",
      totalinUSD: "121,411.97",
    },
    {
      country: {
        value: "Spain",
        img: { src: spainFlag },
      },
      currency: "EUR",
      adminFees: "3,900.00",
      OnOffboardings: "0.00",
      fxRate: "1,5",
      fxBill: "95,000.00",
      benefits: "3,780.00",
      employeeContribution: "0.0",
      totalinUSD: "121,411.97",
    },
  ],
};

export const listData = {
  "customerId": "e291c9f0-2476-4238-85cb-7afecdd085e4",
  "customerName": "DSM Nutritional Products AG",
  "customerLocation": "Switzerland",
  "currencyId": 840,
  "qbInvoiceNo": 21241,
  "invoiceNo": "1001002",
  "status": 3,
  "statusLabel": "Pending Approval",
  "transactionType": 7,
  "transactionTypeLabel": "Contractor Invoice",
  "createdDate": "2022-04-08T00:00:00",
  "paymentDate": null,
  "dueDate": "2022-04-08T00:00:00",
  "exchangeRate": 1,
  "totalAmount": 850,
  "invoiceBalance": 850,
  "isClientVisible": false,
  "depositTo": null,
  "createdBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
  "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
  "poNumber": "4702304768",
  "ageingNotPaid": 5,
  "ageingPaid": null,
  "invoiceDocuments": [],
  "invoiceItems": [],
  "invoiceNotes": [],
  "invoiceRelatedInvoices": [],
  "invoiceRelatedRelatedInvoices": [],
  "payrolls": [],
  "customer": null,
  "currency": {
      "code": "USD",
      "description": "US Dollar",
      "id": 840
  },
  "id": "5e507200-78a1-4708-b389-2a18032ade06"
}

export const apiInvoiceMockData = {
  "invoiceFees": [],
  "countryPayroll": [
      {
          "countryId": "d10b2cb2-d73b-4d73-b981-4372c13f4443",
          "countryName": "Albania",
          "countryCode": "AL",
          "currencyId": 51,
          "currencyCode": "AMD",
          "exchangeRate": 1,
          "employeeContributionCreditTotal": 0,
          "employerContributionTotal": 0,
          "benefitsTotal": 0,
          "feeSummary": {
              "adminFee": 0,
              "boardingFee": 0,
              "hrisFee": 0,
              "fxRate": 0,
              "fxBill": 350,
              "healthCare": 0,
              "eeContribution": 0,
              "total": 0,
              "subTotalDue": 10000,
              "totalCountryVat": 0
          },
          "payrollItems": [
              {
                  "payrollId": "fb706b8f-a622-43a1-a240-8c077e519d71",
                  "countryId": "d10b2cb2-d73b-4d73-b981-4372c13f4443",
                  "currencyId": 51,
                  "employeeId": "KEDSM1677523925",
                  "firstName": "trtre",
                  "lastName": "rerwer",
                  "employeeProfilePicture": null,
                  "totalWage": 0,
                  "allowance": 0,
                  "expenseRe": 10000,
                  "liability": 0,
                  "countryVat": 0,
                  "adminFee": 0,
                  "healthcare": 0,
                  "exchangeRate": 1,
                  "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
                  "isDeleted": false,
                  "isBenefitsCalculationDisabled": false,
                  "country": null,
                  "currency": null,
                  "payroll": null,
                  "payrollItemFees": [],
                  "payrollItemBenefits": null,
                  "id": "d8095533-6b67-4ed3-8b9b-ad09c38ff2d6"
              }
          ],
          "payrollFees": [],
          "benefitsOverviews": []
      },
      {
          "countryId": "2e951b95-2766-40a6-808b-fe614f7bca18",
          "countryName": "Algeria",
          "countryCode": "DZ",
          "currencyId": 51,
          "currencyCode": "AMD",
          "exchangeRate": 1,
          "employeeContributionCreditTotal": 0,
          "employerContributionTotal": 0,
          "benefitsTotal": 0,
          "feeSummary": {
              "adminFee": 1500,
              "boardingFee": 0,
              "hrisFee": 0,
              "fxRate": 0,
              "fxBill": 157.5,
              "healthCare": 2000,
              "eeContribution": 0,
              "total": 3500,
              "subTotalDue": 4500,
              "totalCountryVat": 0
          },
          "payrollItems": [
              {
                  "payrollId": "fb706b8f-a622-43a1-a240-8c077e519d71",
                  "countryId": "2e951b95-2766-40a6-808b-fe614f7bca18",
                  "currencyId": 51,
                  "employeeId": "KEDSM974827474",
                  "firstName": "SHAHANA ",
                  "lastName": "SHA",
                  "employeeProfilePicture": null,
                  "totalWage": 0,
                  "allowance": 3500,
                  "expenseRe": 0,
                  "liability": 1000,
                  "countryVat": 0,
                  "adminFee": 1500,
                  "healthcare": 2000,
                  "exchangeRate": 1,
                  "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
                  "isDeleted": false,
                  "isBenefitsCalculationDisabled": false,
                  "country": null,
                  "currency": null,
                  "payroll": null,
                  "payrollItemFees": [],
                  "payrollItemBenefits": null,
                  "id": "9275ea18-bacb-4d03-89d4-29f3b2ac07a4"
              }
          ],
          "payrollFees": [],
          "benefitsOverviews": []
      },
      {
          "countryId": "7defc4f9-906d-437f-a6d9-c822ca2ecfd7",
          "countryName": "Kenya",
          "countryCode": "KE",
          "currencyId": 51,
          "currencyCode": "AMD",
          "exchangeRate": 1,
          "employeeContributionCreditTotal": 0,
          "employerContributionTotal": 0,
          "benefitsTotal": 0,
          "feeSummary": {
              "adminFee": 0,
              "boardingFee": 0,
              "hrisFee": 0,
              "fxRate": 0,
              "fxBill": 646697.18,
              "healthCare": 0,
              "eeContribution": 0,
              "total": 0,
              "subTotalDue": 18477062.33,
              "totalCountryVat": 0
          },
          "payrollItems": [
              {
                  "payrollId": "fb706b8f-a622-43a1-a240-8c077e519d71",
                  "countryId": "7defc4f9-906d-437f-a6d9-c822ca2ecfd7",
                  "currencyId": 51,
                  "employeeId": "KEDSM645974056",
                  "firstName": "Thomas",
                  "lastName": "George",
                  "employeeProfilePicture": null,
                  "totalWage": 1000,
                  "allowance": 18476062.33,
                  "expenseRe": 0,
                  "liability": 0,
                  "countryVat": 0,
                  "adminFee": 0,
                  "healthcare": 0,
                  "exchangeRate": 1,
                  "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
                  "isDeleted": false,
                  "isBenefitsCalculationDisabled": false,
                  "country": null,
                  "currency": null,
                  "payroll": null,
                  "payrollItemFees": [],
                  "payrollItemBenefits": null,
                  "id": "49eee937-3de8-45de-a048-7dd930e38fc0"
              }
          ],
          "payrollFees": [],
          "benefitsOverviews": []
      }
  ],
  "payrollFees": [
      {
          "payrollId": "fb706b8f-a622-43a1-a240-8c077e519d71",
          "customerCountryId": null,
          "currency": null,
          "payroll": null,
          "feeId": "85506482-83ec-42cc-8448-ddd612fa6242",
          "valueType": 1,
          "value": 100,
          "currencyId": 840,
          "amount": 100,
          "isLocked": false,
          "fee": null,
          "id": "24051129-40e7-46b9-9ea1-c41b4491687d"
      },
      {
          "payrollId": "fb706b8f-a622-43a1-a240-8c077e519d71",
          "customerCountryId": null,
          "currency": null,
          "payroll": null,
          "feeId": "47fb6ed1-5fe2-4cff-9671-b77c352be0f0",
          "valueType": 1,
          "value": 700,
          "currencyId": 840,
          "amount": 700,
          "isLocked": false,
          "fee": null,
          "id": "4d631bf8-0e23-4cd7-9c07-b57574661304"
      }
  ],
  "id": "fb706b8f-a622-43a1-a240-8c077e519d71",
  "periodDate": "2022-04-01T00:00:00",
  "isModified": false,
  "invoiceFrom": {
      "companyName": "Elements Holdings Group Ltd",
      "vatOrGSTNumber": "GB270909295",
      "addressLine1": "41 Corsham Street",
      "addressLine2": "",
      "city": "N1 6DR",
      "state": "London",
      "country": "United Kingdom",
      "phoneNumber": "+44 (0)203 405 8282",
      "email": "invoices@elementsgs.com",
      "website": "www.elementsgs.com"
  },
  "invoice": {
      "vatAmount": 0,
      "customerId": "a9bbee6d-797a-4724-a86a-5b1a2e28763f",
      "customerName": "DSM Nutritional Products AG",
      "customerLocation": "Switzerland",
      "currencyId": 840,
      "qbInvoiceNo": 21241,
      "invoiceNo": "1001002",
      "status": 3,
      "transactionType": 7,
      "createdDate": "2022-04-08T00:00:00",
      "paymentDate": null,
      "dueDate": "2022-04-08T00:00:00",
      "exchangeRate": 1,
      "totalAmount": 850,
      "invoiceBalance": 850,
      "isClientVisible": false,
      "depositTo": null,
      "createdBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
      "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
      "poNumber": "4702304768",
      "ageingNotPaid": 5,
      "ageingPaid": null,
      "invoiceDocuments": [
          {
              "invoiceId": "5e507200-78a1-4708-b389-2a18032ade06",
              "documentId": "103d7c82-d596-4698-8979-048b42681ee5",
              "isCustomerVisible": false,
              "document": {
                  "url": "https://apnguatemeaservices.blob.core.windows.net/data/cd9f001b-d991-478e-9c69-6e9121ba2b69.pdf",
                  "documentType": 1,
                  "documentName": "Payroll-EMEA-5e507200-78a1-4708-b389-2a18032ade06.pdf",
                  "uploadDate": "2022-04-08T12:10:56.43",
                  "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
                  "id": "103d7c82-d596-4698-8979-048b42681ee5"
              }
          }
      ],
      "invoiceItems": [],
      "invoiceNotes": [
          {
              "invoiceId": "5e507200-78a1-4708-b389-2a18032ade06",
              "noteType": 2,
              "note": "CREATED",
              "isCustomerVisible": true,
              "exportToQuickbooks": false,
              "createdDate": "2022-01-29T10:45:22Z",
              "modifiedBy": "48a69262-1054-4d96-830e-8514c78b0eb1",
              "modifiedByUser": {
                  "userName": null,
                  "normalizedUserName": null,
                  "email": null,
                  "normalizedEmail": null,
                  "emailConfirmed": false,
                  "firstName": "Approvpay InfraAdmin",
                  "lastName": "User",
                  "passwordHash": null,
                  "securityStamp": null,
                  "concurrencyStamp": null,
                  "lockoutEnabled": false,
                  "phoneNumber": null,
                  "location": null,
                  "phoneNumberConfirmed": false,
                  "twoFactorEnabled": false,
                  "lockoutEnd": null,
                  "accessFailedCount": 0,
                  "isExternal": false,
                  "realmName": null,
                  "title": null,
                  "customerUsers": [],
                  "id": "48a69262-1054-4d96-830e-8514c78b0eb1"
              },
              "displayInPDF": false,
              "id": 39202
          },
          {
              "invoiceId": "5e507200-78a1-4708-b389-2a18032ade06",
              "noteType": 2,
              "note": "APPROVED",
              "isCustomerVisible": true,
              "exportToQuickbooks": false,
              "createdDate": "2022-03-24T14:09:31.25Z",
              "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
              "modifiedByUser": {
                  "userName": null,
                  "normalizedUserName": null,
                  "email": null,
                  "normalizedEmail": null,
                  "emailConfirmed": false,
                  "firstName": "Approvpay InfraAdmin",
                  "lastName": "User",
                  "passwordHash": null,
                  "securityStamp": null,
                  "concurrencyStamp": null,
                  "lockoutEnabled": false,
                  "phoneNumber": null,
                  "location": null,
                  "phoneNumberConfirmed": false,
                  "twoFactorEnabled": false,
                  "lockoutEnd": null,
                  "accessFailedCount": 0,
                  "isExternal": false,
                  "realmName": null,
                  "title": null,
                  "customerUsers": [],
                  "id": "eed924b3-97b1-4133-b6a0-10e00df7014e"
              },
              "displayInPDF": false,
              "id": 39211
          },
          {
              "invoiceId": "5e507200-78a1-4708-b389-2a18032ade06",
              "noteType": 2,
              "note": "SENT FOR REVIEW",
              "isCustomerVisible": true,
              "exportToQuickbooks": false,
              "createdDate": "2022-04-08T12:06:09.12Z",
              "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
              "modifiedByUser": {
                  "userName": null,
                  "normalizedUserName": null,
                  "email": null,
                  "normalizedEmail": null,
                  "emailConfirmed": false,
                  "firstName": "Approvpay InfraAdmin",
                  "lastName": "User",
                  "passwordHash": null,
                  "securityStamp": null,
                  "concurrencyStamp": null,
                  "lockoutEnabled": false,
                  "phoneNumber": null,
                  "location": null,
                  "phoneNumberConfirmed": false,
                  "twoFactorEnabled": false,
                  "lockoutEnd": null,
                  "accessFailedCount": 0,
                  "isExternal": false,
                  "realmName": null,
                  "title": null,
                  "customerUsers": [],
                  "id": "eed924b3-97b1-4133-b6a0-10e00df7014e"
              },
              "displayInPDF": false,
              "id": 39246
          },
          {
              "invoiceId": "5e507200-78a1-4708-b389-2a18032ade06",
              "noteType": 2,
              "note": "APPROVED",
              "isCustomerVisible": true,
              "exportToQuickbooks": false,
              "createdDate": "2022-04-08T12:10:05.097Z",
              "modifiedBy": "eed924b3-97b1-4133-b6a0-10e00df7014e",
              "modifiedByUser": {
                  "userName": null,
                  "normalizedUserName": null,
                  "email": null,
                  "normalizedEmail": null,
                  "emailConfirmed": false,
                  "firstName": "Approvpay InfraAdmin",
                  "lastName": "User",
                  "passwordHash": null,
                  "securityStamp": null,
                  "concurrencyStamp": null,
                  "lockoutEnabled": false,
                  "phoneNumber": null,
                  "location": null,
                  "phoneNumberConfirmed": false,
                  "twoFactorEnabled": false,
                  "lockoutEnd": null,
                  "accessFailedCount": 0,
                  "isExternal": false,
                  "realmName": null,
                  "title": null,
                  "customerUsers": [],
                  "id": "eed924b3-97b1-4133-b6a0-10e00df7014e"
              },
              "displayInPDF": false,
              "id": 39247
          }
      ],
      "invoiceRelatedInvoices": [],
      "invoiceRelatedRelatedInvoices": [],
      "payrolls": null,
      "customer": null,
      "currency": null,
      "id": "5e507200-78a1-4708-b389-2a18032ade06"
  },
  "regionItemCode": "emea"
};
export const mockLogsdata = [
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '1 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '2 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '3 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '4 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '5 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '6 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '7 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '8 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '9 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '10 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '11 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '12 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '13 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '14 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '15 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '16 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '17 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '18 changed Benefits Plan and Pay item for this employee.' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '19 changed Annual Salary for this employee' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '20 submitted Invoice for Review' },
  { date: new Date().toDateString(), customerEmail: 'danielal@email.com', description: '21 changed Benefits Plan and Pay item for this employee.' }
];
// export const payrollData = {
//   columns: [
//     {
//       header: "Employee ID",
//       isDefault: true,
//       key: "employeeID",
//     },
//     {
//       header: "Name",
//       isDefault: true,
//       key: "name",
//     },
//     {
//       header: "Gross Wages",
//       isDefault: true,
//       key: "grossWages",
//     },
//     {
//       header: "Allowances",
//       isDefault: true,
//       key: "allowances",
//     },
//     {
//       header: "Expense Reimb.",
//       isDefault: true,
//       key: "expenseReimb",
//     },
//     {
//       header: "Employer Liability",
//       isDefault: true,
//       key: "employerLiability",
//     },
//     {
//       header: "Country VAT",
//       isDefault: true,
//       key: "countryVAT",
//     },
//     {
//       header: "Admin Fees",
//       isDefault: true,
//       key: "adminFees",
//     },
//     {
//       header: "Healthcare Benefits",
//       isDefault: true,
//       key: "healthcareBenefits",
//     },
//   ],
//   showDefaultColumn: true,
//   data: [
//     {
//       employeeID: "73917",
//       name: {
//         value: "Marcos Rodriguez",
//         img: { src: user },
//       },
//       grossWages: "EUR 32,000.00",
//       allowances: "EUR 0.00",
//       expenseReimb: "EUR 0.00",
//       employerLiability: "EUR 7,210.00",
//       countryVAT: "0.63",
//       adminFees: "USD 650.00",
//       healthcareBenefits: "USD 1260.00",
//     },
//     {
//       employeeID: "73917",
//       name: {
//         value: "Marcos Rodriguez",
//         img: { src: user },
//       },
//       grossWages: "EUR 32,000.00",
//       allowances: "EUR 0.00",
//       expenseReimb: "EUR 0.00",
//       employerLiability: "EUR 7,210.00",
//       countryVAT: "0.63",
//       adminFees: "USD 650.00",
//       healthcareBenefits: "USD 1260.00",
//     },
//     {
//       employeeID: "73917",
//       name: {
//         value: "Marcos Rodriguez",
//         img: { src: user },
//       },
//       grossWages: "EUR 32,000.00",
//       allowances: "EUR 0.00",
//       expenseReimb: "EUR 0.00",
//       employerLiability: "EUR 7,210.00",
//       countryVAT: "0.63",
//       adminFees: "USD 650.00",
//       healthcareBenefits: "USD 1260.00",
//     },
//     {
//       employeeID: "73917",
//       name: {
//         value: "Marcos Rodriguez",
//         img: { src: user },
//       },
//       grossWages: "EUR 32,000.00",
//       allowances: "EUR 0.00",
//       expenseReimb: "EUR 0.00",
//       employerLiability: "EUR 7,210.00",
//       countryVAT: "0.63",
//       adminFees: "USD 650.00",
//       healthcareBenefits: "USD 1260.00",
//     },
//   ],
// };
