import avatar from '../InvoiceDetails/avatar.png'
export const BillsByInvoiceId = [
    {
        billReferenceNo : 791233,
        contractorName: "Camila Lopez",
        contractorProfilePicSrc: avatar,
        contractorId: 791233,
        countryCode: "ES",
        countryName: "Spain",
        billingCurrencyCode: "EUR",
        payAmmount: 25000,
        exchangeRate: 1.10,
        adminFee: 50.00,
        adminCurrecyCode: "USD",
    },
    {
        billReferenceNo : 779852,
        contractorName: "Mo Salah",
        contractorProfilePicSrc: avatar,
        contractorId: 791233,
        countryCode: "gb",
        countryName: "England",
        billingCurrencyCode: "EUR",
        payAmmount: 255000,
        exchangeRate: 1.10,
        adminFee: 50.00,
        adminCurrecyCode: "USD",
    },
    {
        billReferenceNo : 784587,
        contractorName: "Roberto Firmino",
        contractorProfilePicSrc: avatar,
        contractorId: 791233,
        countryCode: "gb",
        countryName: "England",
        billingCurrencyCode: "EUR",
        payAmmount: 250800,
        exchangeRate: 1.10,
        adminFee: 50.00,
        adminCurrecyCode: "USD",
    },
]